<a href="https://colab.research.google.com/github/SohanKumar56/23102A0056_RPROGRAMMING/blob/main/Week9_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Formatting and Display of Strings

In [1]:
print("the zero occurs at");print(2*pi); print("radians")

[1] "the zero occurs at"
[1] 6.283185
[1] "radians"

In [2]:
cat("The zero occurs at", 2*pi,"radians.","\n")

The zero occurs at 6.283185 radians.

In [3]:
d= date()
cat("Today's date is:", d, "\n")

Today's date is: Thu Sep 24 03:57:03 2026

In [4]:
x=1:10

In [5]:
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [11]:
cat(x, sep=" ++ ")

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10

In [14]:
cat("\n")

In [12]:
cat(x, sep="/")

1/2/3/4/5/6/7/8/9/10

In [15]:
x=7
cat("The square of", x, "is", x^2, "!\n")

The square of 7 is 49 !

In [16]:
cat("The square root of", x, "is approximately", format(sqrt(x), digits=3), "\n")

The square root of 7 is approximately 2.65

In [17]:
evenno = c(2,4,6,8,10)
evenno

[1]  2  4  6  8 10

In [19]:
cat("The first few even numbers are:", evenno, "....\n")

The first few even numbers are: 2 4 6 8 10 ....

In [20]:
x= 1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [21]:
cat(x, fill=2, labels =paste("(", letters[1:10],"):"))

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

In [24]:
paste(1:!2)

[1] "1" "0"

In [25]:
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [26]:
as.character(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [27]:
paste("Everybody","loves","R programming.")

[1] "Everybody loves R programming."

In [28]:
paste("Everybody", "loves","R Programming.", sep="*")

[1] "Everybody*loves*R Programming."

In [29]:
paste("Sunday", "runday",sep="==")

[1] "Sunday==runday"

In [31]:
names=c("Prof. Singh", "Mr. Venkat", "Dr. Jha")
names

[1] "Prof. Singh" "Mr. Venkat"  "Dr. Jha"

In [32]:
paste(names, "is a good person")

[1] "Prof. Singh is a good person" "Mr. Venkat is a good person"
[3] "Dr. Jha is a good person"

In [34]:
paste(names, "is a good person.", collapse = " and ")

[1] "Prof. Singh is a good person. and Mr. Venkat is a good person. and Dr. Jha is a good person."

In [38]:
paste(1, "is first", 2, "is second", 3, "is third", sep=" #")

[1] "1 #is first #2 #is second #3 #is third"

In [39]:
x = paste("Ex", 1:5, sep="_")

In [40]:
x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [41]:
x[1]

[1] "Ex_1"

In [45]:
x[3]

[1] "Ex_3"

In [46]:
x=paste("Ex", 1:5, sep="_", collapse = "")

In [47]:
x

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [48]:
paste0(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [49]:
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [50]:
paste0(1:10, c("st", "nd", "rd", rep("th",7)))

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

In [51]:
paste(1:10, c("st", "nd", "rd", rep("th",7)))

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

In [52]:
x = "The&!syntax&!of&!paste&!is!&available!&inthe online-help"

In [53]:
strsplit(x,split="!")

[[1]]
[1] "The&"               "syntax&"            "of&"
[4] "paste&"             "is"                 "&available"
[7] "&inthe online-help"

In [54]:
strsplit(x,split="&!")

[[1]]
[1] "The"                              "syntax"
[3] "of"                               "paste"
[5] "is!&available!&inthe online-help"

In [55]:
x

[1] "The&!syntax&!of&!paste&!is!&available!&inthe online-help"

In [56]:
y = strsplit(x, split="!&")

In [57]:
y

[[1]]
[1] "The&!syntax&!of&!paste&!is" "available"
[3] "inthe online-help"

In [58]:
y[[1]][1]

[1] "The&!syntax&!of&!paste&!is"

In [60]:
y[[1]][2]

[1] "available"

In [61]:
y[[1]][4]

[1] NA

In [62]:
dates= c("2020-07-24","2020-08-26","2022-09-27")

In [63]:
datesplt= strsplit(dates, "-")

In [64]:
datesplt

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2020" "08"   "26"

[[3]]
[1] "2022" "09"   "27"

In [66]:
datemat = matrix(unlist(datesplt), nrow=3, ncol=3, byrow= TRUE)

In [67]:
datemat

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2020 08   26
[3,] 2022 09   27

In [68]:
datemat = matrix(as.numeric(unlist(datesplt)), nrow=3, ncol=3, byrow= TRUE)

In [69]:
datemat

     [,1] [,2] [,3]
[1,] 2020 7    24
[2,] 2020 8    26
[3,] 2022 9    27

In [71]:
strsplit("Sohan", split="")

[[1]]
[1] "S" "o" "h" "a" "n"

In [72]:
x= "R course 24.07.2022"

y= "Number of participants: 25"

In [74]:
nchar(x)

[1] 19

In [76]:
nchar(y)

[1] 26

In [77]:
nzchar(x)

[1] TRUE

In [78]:
nzchar(y)

[1] TRUE

In [79]:
x = c("Apple", "Banana", "Cake")
nzchar(x)

[1] TRUE TRUE TRUE

In [80]:
x = c("Apple", "", "Cake")
nzchar(x)

[1]  TRUE FALSE  TRUE

In [82]:
x = c("Apple", "Banana", "Cake")
nchar(x)

[1] 5 6 4

In [84]:
x = c(2,4,6)
nchar(x)

[1] 1 1 1

In [85]:
x = c(2342,433,006)
nchar(x)

[1] 4 3 1

In [86]:
 x = "R course will start from 24.07.2022"
 toupper(x)

[1] "R COURSE WILL START FROM 24.07.2022"

In [87]:
z="INDIA Is great"
tolower(z)

[1] "india is great"