<a href="https://colab.research.google.com/github/SohanKumar56/23102A0056_RPROGRAMMING/blob/main/Week7_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Sohan Kumar

Roll No.: 23102A0056

Branch: CMPN-A

# Sequences

In [1]:
1:10

 [1]  1  2  3  4  5  6  7  8  9 10

In [2]:
10:1

 [1] 10  9  8  7  6  5  4  3  2  1

In [3]:
5:15

 [1]  5  6  7  8  9 10 11 12 13 14 15

In [4]:
15:5

 [1] 15 14 13 12 11 10  9  8  7  6  5

In [5]:
-1:-10

 [1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10

In [6]:
-10:-1

 [1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1

In [7]:
-5:-15

 [1]  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15

In [8]:
-15:-5

 [1] -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5

In [9]:
1.23:10

[1] 1.23 2.23 3.23 4.23 5.23 6.23 7.23 8.23 9.23

In [10]:
1.23:10.54

 [1]  1.23  2.23  3.23  4.23  5.23  6.23  7.23  8.23  9.23 10.23

In [11]:
10.54:2.23

[1] 10.54  9.54  8.54  7.54  6.54  5.54  4.54  3.54  2.54

In [12]:
-1.23: -10

[1] -1.23 -2.23 -3.23 -4.23 -5.23 -6.23 -7.23 -8.23 -9.23

In [13]:
-5.23:6

 [1] -5.23 -4.23 -3.23 -2.23 -1.23 -0.23  0.77  1.77  2.77  3.77  4.77  5.77

In [14]:
seq(10)

 [1]  1  2  3  4  5  6  7  8  9 10

In [15]:
seq(1:10)

 [1]  1  2  3  4  5  6  7  8  9 10

In [16]:
x=2
seq(1,x,x/10)

[1] 1.0 1.2 1.4 1.6 1.8 2.0

In [17]:
x=50
seq(0,x,x/10)

 [1]  0  5 10 15 20 25 30 35 40 45 50

In [19]:
x=seq(1,50,1/2)
x

 [1]  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0
[16]  8.5  9.0  9.5 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 14.5 15.0 15.5
[31] 16.0 16.5 17.0 17.5 18.0 18.5 19.0 19.5 20.0 20.5 21.0 21.5 22.0 22.5 23.0
[46] 23.5 24.0 24.5 25.0 25.5 26.0 26.5 27.0 27.5 28.0 28.5 29.0 29.5 30.0 30.5
[61] 31.0 31.5 32.0 32.5 33.0 33.5 34.0 34.5 35.0 35.5 36.0 36.5 37.0 37.5 38.0
[76] 38.5 39.0 39.5 40.0 40.5 41.0 41.5 42.0 42.5 43.0 43.5 44.0 44.5 45.0 45.5
[91] 46.0 46.5 47.0 47.5 48.0 48.5 49.0 49.5 50.0

In [21]:
y=2*x
y

 [1]   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
[20]  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
[39]  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
[58]  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
[77]  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
[96]  97  98  99 100

In [24]:
x=c(9,8,7,6)
ind= seq(along=x)
ind

[1] 1 2 3 4

In [26]:
x[ind[2]]

[1] 8

### Sequences of dates

In [27]:
Sys.time()

[1] "2026-09-03 04:15:21 UTC"

In [29]:
Sys.Date()

[1] "2026-09-03"

In [35]:
seq(as.Date("2010-01-01"), as.Date("2017-01-01"), by="years")

[1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
[6] "2015-01-01" "2016-01-01" "2017-01-01"

In [37]:
seq(as.Date("2021-8-31"), by="days", length=6)

[1] "2021-08-31" "2021-09-01" "2021-09-02" "2021-09-03" "2021-09-04"
[6] "2021-09-05"

In [39]:
seq(as.Date("2021-8-30"), by="months", length=6)

[1] "2021-08-30" "2021-09-30" "2021-10-30" "2021-11-30" "2021-12-30"
[6] "2022-01-30"

In [40]:
seq(as.Date("2021-8-31"), by="months", length=6) #see the difference , it is validating date too it was expected that 2021-09-31 should be the second element but there are only 30 days in Sept month so it jumped to next month i.e Oct

[1] "2021-08-31" "2021-10-01" "2021-10-31" "2021-12-01" "2021-12-31"
[6] "2022-01-31"

In [44]:
seq(as.Date("2021-02-29"), by="months", length=6) # you got this error because Year 2021 was not a leap year

ERROR: Error in charToDate(x): character string is not in a standard unambiguous format

In [48]:
seq(as.Date("2021-02-29"), by="days", length=6) # you got this error because Year 2021 was not a leap year

ERROR: Error in charToDate(x): character string is not in a standard unambiguous format

In [50]:
startdate=as.Date("2016-01-01")
enddate=as.Date("2017-01-01")

out=seq(enddate,startdate,by="-1 month")
out

 [1] "2017-01-01" "2016-12-01" "2016-11-01" "2016-10-01" "2016-09-01"
 [6] "2016-08-01" "2016-07-01" "2016-06-01" "2016-05-01" "2016-04-01"
[11] "2016-03-01" "2016-02-01" "2016-01-01"

### letters and LETTERS

In [51]:
letters

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [53]:
letters[1:3]

[1] "a" "b" "c"

In [56]:
letters[3:1]

[1] "c" "b" "a"

In [60]:
letters[20:25]

[1] "t" "u" "v" "w" "x" "y"

In [61]:
letters[2]

[1] "b"

In [52]:
LETTERS

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [62]:
LETTERS[2:5]

[1] "B" "C" "D" "E"

In [64]:
LETTERS[34:56] # checkout this it returns NA if out of range values are given

 [1] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA

In [69]:
LETTERS[10:3]

[1] "J" "I" "H" "G" "F" "E" "D" "C"

# Repeats

In [70]:
rep(3.5, times=2)

[1] 3.5 3.5

In [71]:
rep(1:5, 2)

 [1] 1 2 3 4 5 1 2 3 4 5

In [72]:
x=1:4
rep(x,each=3)

 [1] 1 1 1 2 2 2 3 3 3 4 4 4

In [73]:
rep(x,each=3,times=4)

 [1] 1 1 1 2 2 2 3 3 3 4 4 4 1 1 1 2 2 2 3 3 3 4 4 4 1 1 1 2 2 2 3 3 3 4 4 4 1 1
[39] 1 2 2 2 3 3 3 4 4 4

In [74]:
rep(x,times=4,each=3)

 [1] 1 1 1 2 2 2 3 3 3 4 4 4 1 1 1 2 2 2 3 3 3 4 4 4 1 1 1 2 2 2 3 3 3 4 4 4 1 1
[39] 1 2 2 2 3 3 3 4 4 4

In [78]:
rep(1:4, 2:5)

 [1] 1 1 2 2 2 3 3 3 3 4 4 4 4 4

In [82]:
ans = seq(from=1, to=8, by=2)
ans

[1] 1 3 5 7

In [83]:
rep(1:4, ans)

 [1] 1 2 2 2 3 3 3 3 3 4 4 4 4 4 4 4

In [84]:
x= matrix(nrow=2, ncol=2, dat=1:4, byrow = T)

In [85]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4

In [86]:
rep(x,3)

 [1] 1 3 2 4 1 3 2 4 1 3 2 4

In [87]:
rep(c("a",'b','c'),2)

[1] "a" "b" "c" "a" "b" "c"

In [88]:
rep(c("ai",'bigdata','catboost'),2)

[1] "ai"       "bigdata"  "catboost" "ai"       "bigdata"  "catboost"

In [89]:
rep(2, length.out=5)

[1] 2 2 2 2 2

In [90]:
rep(2, length=5)

[1] 2 2 2 2 2

In [91]:
rep(c("ai",'bigdata','catboost'), length=5)

[1] "ai"       "bigdata"  "catboost" "ai"       "bigdata"

In [92]:
rep(c("ai",'bigdata','catboost'), length=2)

[1] "ai"      "bigdata"

#Sorting

In [93]:
y=c(8,5,7,6)
y

[1] 8 5 7 6

In [94]:
sort(y)

[1] 5 6 7 8

In [95]:
sort(y, decreasing=TRUE)

[1] 8 7 6 5

In [96]:
sort(y, decreasing=FALSE)

[1] 5 6 7 8

In [99]:
z=c("Soham", "Sohan", "Bro")
sort(z, decreasing=TRUE)

[1] "Sohan" "Soham" "Bhai"

In [101]:
z=c("Soham", "Sohan", "Bro")
sort(z, decreasing=FALSE)

[1] "Bro"   "Soham" "Sohan"

#Ordering

In [105]:
y=c(9,-5,56,5)
y

[1]  9 -5 56  5

In [106]:
order(y)

[1] 2 4 1 3

In [107]:
order(y, decreasing = TRUE)

[1] 3 1 4 2

#Mode

In [108]:
mode(2.432)

[1] "numeric"

In [109]:
mode(c(2,4,3))

[1] "numeric"

In [110]:
mode("India")

[1] "character"

In [111]:
mode(c("India", "2"))

[1] "character"

In [112]:
mode(c("India", 1))

[1] "character"

In [113]:
mode(c(3,"India", 1))

[1] "character"

In [114]:
mode(c(3,4.5, 1))

[1] "numeric"

In [115]:
mode(factor(c(3,"India", 1)))

[1] "numeric"

In [116]:
mode(list("India","Tibet"))

[1] "list"

In [120]:
l=data.frame(x=1:2, y=c("India", "USA"))
l

  x y
1 1 India
2 2 USA

In [118]:
mode(data.frame(x=1:2, y=c("India", "USA")))

[1] "list"

In [121]:
mode(print)

[1] "function"

#Lists

In [124]:
x1=matrix(nrow=2,ncol=2, data=1:4,byrow=T)
x2=matrix(nrow=2,ncol=2, data=10:13,byrow=T)

In [125]:
x3=x1+x2

In [126]:
x3

     [,1] [,2]
[1,] 11   13
[2,] 15   17

In [127]:
x1[2,1] = "hello"

In [128]:
x1 + x2

ERROR: Error in x1 + x2: non-numeric argument to binary operator

In [129]:
matlist=list(x1,x2)

In [130]:
matlist

[[1]]
     [,1]    [,2]
[1,] "1"     "2"
[2,] "hello" "4"

[[2]]
     [,1] [,2]
[1,]   10   11
[2,]   12   13

In [131]:
matlist[1]

[[1]]
     [,1]    [,2]
[1,] "1"     "2"
[2,] "hello" "4"

In [132]:
matlist[2]

[[1]]
     [,1] [,2]
[1,]   10   11
[2,]   12   13

In [135]:
z1=list(c("water","juice","lemonade") , rep(1:4, each=2), matrix(data=5:8,nrow=2, ncol=2, byrow=T))

In [136]:
z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [137]:
z1[[1]]

[1] "water"    "juice"    "lemonade"

In [138]:
z1[1] #it gives Sr No. too

[[1]]
[1] "water"    "juice"    "lemonade"

In [139]:
z1[2]

[[1]]
[1] 1 1 2 2 3 3 4 4

In [140]:
z1[[3]]

     [,1] [,2]
[1,] 5    6
[2,] 7    8

In [141]:
z1[1][2]

[[1]]
NULL

In [142]:
z1[[1]][2]

[1] "juice"