<a href="https://colab.research.google.com/github/SohanKumar56/23102A0056_RPROGRAMMING/blob/main/Week3_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Sohan Kumar

Roll no: 23102A0056

Branch: CMPN-A

In [3]:
#addition with data vectors

c(2,3,5,7) + c(-2,-3,-4,-6)

[1] 0 0 1 1

In [14]:
# R as a calculator

2^3

2**3

2^0.5

2**0.5

2**-0.5

[1] 8

[1] 8

[1] 1.414214

[1] 1.414214

[1] 0.7071068

In [15]:
# Power Operator with scalar

c(2,3,4,7)^2

[1]  4  9 16 49

In [16]:
#power operation with vector
c(2,3,4,7)^c(2,3)

[1]   4  27  16 343

In [17]:
c(2,3,4,5)**c(2,3,4)

Warning message in c(2, 3, 4, 5)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 256  25

In [18]:
#integer division with scalar
c(2,3,4,5)%/%2

[1] 1 1 2 2

In [19]:
#integer division with data vector
c(2,3,4,5)%/%c(2,3)

[1] 1 1 2 1

In [20]:
#integer division with scalar
c(2,3,4,5)%/%c(2,3,4)

Warning message in c(2, 3, 4, 5)%/%c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1] 1 1 1 2

In [22]:
#modulo division (x mod y) with scalars

2 %% 2

3 %% 2

7 %% 3

7 %% 4

[1] 0

[1] 1

[1] 1

[1] 3

In [23]:
#modulo division of vectors (x mod y) with scalars

c(2,3,4,5) %% 2

[1] 0 1 0 1

In [24]:
#modulo division of vectors (x mod y) with data vectors

c(2,3,4,5) %% c(2,4)

[1] 0 3 0 1

In [25]:
c(2,3,4,5) %% c(2,4,5)

Warning message in c(2, 3, 4, 5)%%c(2, 4, 5):
“longer object length is not a multiple of shorter object length”

[1] 0 3 4 1

In [27]:
#Maximum

max(2.3, 4.5, 4.7, -4)


max(c(2.3, 4.5, 4.7, -4))

[1] 4.7

[1] 4.7

In [28]:
#Minimum

min(2.3, 4.5, 4.7, -4)


min(c(2.3, 4.5, 4.7, -4))

[1] -4

[1] -4

In [29]:
# mean

mean(2,3,4)

[1] 2

In [30]:
mean(c(2,3,4))

[1] 3

###Overview of further functions

In [31]:
abs(-4)

[1] 4

In [32]:
abs(c(-2,4,-3,-8.9))

[1] 2.0 4.0 3.0 8.9

In [33]:
sqrt(4)

[1] 2

In [34]:
sqrt(c(4,9,18,25))

[1] 2.000000 3.000000 4.242641 5.000000

In [35]:
sum(c(2,3,5,7))

[1] 17

In [36]:
prod(c(2,3,4,5))

[1] 120

In [37]:
round(1.23)

[1] 1

In [38]:
round(1.82)

[1] 2

In [39]:
log(10)

[1] 2.302585

In [42]:
log(exp(1))

[1] 1

In [43]:
log(c(10,100,1000))

[1] 2.302585 4.605170 6.907755

In [44]:
log10(10)

[1] 1

In [45]:
log10(100)

[1] 2

In [47]:
log10(2)

[1] 0.30103

In [48]:
log10(c(10,100,1000))

[1] 1 2 3

In [51]:
#Assignments


x1= c(1,2,3,4)
x1

[1] 1 2 3 4

In [53]:
x2= x1^2
x2

[1]  1  4  9 16

In [54]:
c(1,2,3,4) + sum(c(1,2,3,4)) + prod(c(1,2))

[1] 13 14 15 16

In [56]:
c(1,2,3,4) - sum(c(1,2,3,4)) * prod(c(1,2))

[1] -19 -18 -17 -16

In [55]:
abs(c(1,2,3,4) - sum(c(1,2,3,4)) * prod(c(1,2)))

[1] 19 18 17 16

#Matrix

In [59]:
x=matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))

In [60]:
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [62]:
x[3,2]

[1] 7

In [63]:
x=matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow=TRUE)

In [64]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [65]:
dim(x)

[1] 4 2

In [66]:
nrow(x)

[1] 4

In [67]:
ncol(x)

[1] 2

In [68]:
mode(x)

[1] "numeric"

In [69]:
attributes(x)

$dim
[1] 4 2